heat_template_version: 2013-05-23

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: ubuntuCloud14
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
    default: my_key1
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach server to.
    default: my_net1
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach server to.
    default: admin_floating_net

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: LAMP_security_group
      rules:
        - port_range_min: 80
          port_range_max: 80
          protocol: tcp
          direction: ingress
        - port_range_min: 80
          port_range_max: 80
          protocol: tcp
          direction: egress
  client:
    type: https://raw.githubusercontent.com/lpejak/ServiceComposition/master/heat/client.py
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      service1_server: { get_attr: [server1, ip] }
      service2_server: { get_attr: [server2, ip] }
      service3_server: { get_attr: [server3, ip] }
      security_group: { get_resource: security_group }
  server1:
    type: https://raw.githubusercontent.com/lpejak/ServiceComposition/master/heat/server1.py
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      security_group: { get_resource: security_group }
  server2:
    type: https://raw.githubusercontent.com/lpejak/ServiceComposition/master/heat/server2.py
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      security_group: { get_resource: security_group }
  server3:
    type: https://raw.githubusercontent.com/lpejak/ServiceComposition/master/heat/server3.py
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_param: key }
      private_network: { get_param: private_network }
      public_network: { get_param: public_network }
      security_group: { get_resource: security_group }
